### ISSUE TITLE
Full Fledged E-commerce website.

### ISSUE THREAD

**Issue by singhcoder694** [Kritika30032002/ReactCreations#100]
### Project title
E-COMMERCE WEBSITE

### Project Description
It is website which gives a good descritption of how a Ecommerce website should look like. It is working website having so many E-commerce facilities like Adding a **Product, Updating a Product, Showing Description of Product, Deleting Product**

### Web stack
1.) ReactJS
2.) HTML, CSS and JS
3.) Bootstrap 5
4.) API (GET, PUT, POST, PATCH, DELETE)

### Screenshot

**Home Page**
<img width="885" alt="Screenshot 2023-12-10 114036" src="https://github.com/apu52/METAVERSE/assets/114601400/a19b1f1a-4e34-49ab-bbb5-ec1d741ed100">

**Product Page**
<img width="913" alt="Screenshot 2023-12-10 114128" src="https://github.com/apu52/METAVERSE/assets/114601400/2b90a063-965d-4cfb-8f02-d2eabca60cbc">

**Client Views**
<img width="910" alt="Screenshot 2023-12-10 114144" src="https://github.com/apu52/METAVERSE/assets/114601400/3550bfd5-0b74-4575-af69-0dc1dfe14671">

**Footer**
<img width="939" alt="Screenshot 2023-12-10 114152" src="https://github.com/apu52/METAVERSE/assets/114601400/4b6abdfe-d00b-4efc-b4f7-0c2b359931e9">

Contributin Under CodePeak'23

<hr/>

**Comment by Dhruv127** [comment]
kindly assign me the issue
