### ISSUE TITLE
React job portal website

### ISSUE THREAD

**Issue by Dhruv127** [Kritika30032002/ReactCreations#107]
features:
searching the top jobs from top-reputed companies all over the world.
functionalities of searching and filter jobs on based of their job role or experience
has a form where a company user who wants to add their job on to our site can fill the form and add it. 
it has an option where a student/user can save the job by clicking on bookmark icon.

**Comment by AbhineshJha** [comment]
@Kritika30032002 !! I wanna work on this issue, can u assign me ?

**Comment by AbhineshJha** [comment]
Here One thing I have to clear is - Here I have to create just a landing page of portal website na .?

**Comment by Kritika30032002** [comment]
no it will be proper website

**Comment by Kritika30032002** [comment]
displaying job opportunities from various portals

**Comment by AbhineshJha** [comment]
ok !

**Comment by hemant933** [comment]
assign it to me
