### ISSUE TITLE
a Cloths Browsing and Buying WebApp

### ISSUE THREAD

**Issue by Sami3160** [Kritika30032002/ReactCreations#109]
it will be in react where peoples can see different verity of cloths or wear with categorized fashion, gender, age etc

**Comment by piyusesh** [comment]
@Kritika30032002 Please assign me this i want to contribute

**Comment by Bhupendra3444** [comment]
hey @Kritika30032002  Please assign me this task under iwoc. I want to work on it.

**Comment by Kritika30032002** [comment]
@piyusesh  Are u working on this?

**Comment by Sami3160** [comment]
> @piyusesh Are u working on this?

Hey @Kritika30032002 I'm not working under iwoc program but I wann remind that this issue is resolved by me a month ago... By name Shipping wears... I just changed name but I have completed this project under codepeak

**Comment by Kritika30032002** [comment]
Okay thanks for letting me know.
