### ISSUE TITLE
Dictionary App using Free Dictionary API

### ISSUE THREAD

**Issue by drockparashar** [Kritika30032002/ReactCreations#111]
It is an easy-to-use dictionary website made with React.js and the Free Dictionary API. It has a minimal design that works well on computers and phones. It quickly gives you word meanings using the API. 

![image](https://github.com/Kritika30032002/ReactCreations/assets/118686637/af8a7499-89fe-4d10-97f4-3eb485f7df2d)

**Comment by Kritika30032002** [comment]
program name?

**Comment by drockparashar** [comment]
Codepeak 23
