### ISSUE TITLE
[Project]  - To Do Webapp

### ISSUE THREAD

**Issue by AaadityaG** [Kritika30032002/ReactCreations#125]
![AaadityaG_To-do-webapp - Google Chrome 20-12-2023 09_11_25 PM](https://github.com/Kritika30032002/ReactCreations/assets/114663382/4210bcb2-8f05-480c-9644-c3b0ad081555)

**Comment by Tanishka023** [comment]
Hey @AaadityaG !! Can you please assign this to me.

**Comment by AaadityaG** [comment]
I have given you issue already, let me do it!
