### ISSUE TITLE
[project] Stackr

### ISSUE THREAD

**Issue by Mayank77maruti** [Kritika30032002/ReactCreations#127]
Stackr is a game where you would stack blocks on top of each other.

screenshot
![towerblock](https://github.com/Kritika30032002/ReactCreations/assets/125661248/64fa3438-d01b-45bb-8316-c39e4e15c602)

**Comment by Kritika30032002** [comment]
program name?

**Comment by Mayank77maruti** [comment]
CodePeak'23

**Comment by Mayank77maruti** [comment]
Hey @Kritika30032002 , I have made a PR regarding this task , please do review it.
