### ISSUE TITLE
Hangman Game

### ISSUE THREAD

**Issue by drockparashar** [Kritika30032002/ReactCreations#130]
It is the classical hangman game made using React JS.
![image](https://github.com/Kritika30032002/ReactCreations/assets/118686637/e2676edf-2926-4fce-95d5-44ae130e2e46)

**Comment by Kritika30032002** [comment]
program name?

**Comment by drockparashar** [comment]
Codepeak 23

**Comment by drockparashar** [comment]
I have got an issue. I pushed the hangman game along with react dictionary app in the issue no #111 . Please look into it.
