### ISSUE TITLE
Web3-cardGame using react and solidity(blockchain)

### ISSUE THREAD

**Issue by maadi7** [Kritika30032002/ReactCreations#134]
@Kritika30032002  This is a web3 card-game that utilizes the functionality of react, blockchain, smart contracts to make the game more fair and interesting.

![pp](https://github.com/Kritika30032002/ReactCreations/assets/95737654/047d0bc6-a4bb-490c-9877-ea9a18ffb60d)

**Comment by Kritika30032002** [comment]
program name?

**Comment by maadi7** [comment]
@Kritika30032002 hii, please assign me this under codepeak program my project name is web3-cardgame-avaxgods.

**Comment by Bayyana-kiran** [comment]
hey @Kritika30032002 can u assign me i could work on this and also learn about web3

**Comment by Kritika30032002** [comment]
@Bayyana-kiran r u working on this?

**Comment by Bayyana-kiran** [comment]
sorry for the delay and kindly check the PR @Kritika30032002

**Comment by Kritika30032002** [comment]
update readme and show video

**Comment by Bayyana-kiran** [comment]
Kindly check the updated readme file?
