### ISSUE TITLE
ADD "THE HOOKS" PROJECTS

### ISSUE THREAD

**Issue by GAGANRAGHAV** [Kritika30032002/ReactCreations#138]
a linking website made using react , firebase . aim is to link the underprivileged orphaned children with the lonely, disadvantaged elderly.

screenshot--

![image](https://github.com/Kritika30032002/ReactCreations/assets/120806356/23bf8f72-015f-4e04-9a3c-11672fbcde02)

**Comment by Kritika30032002** [comment]
are your projects originally yours?
there shouldn't be any copyright issue later

**Comment by GAGANRAGHAV** [comment]
yes ma'am they are my college own made projects.

**Comment by GAGANRAGHAV** [comment]
ma'am please assign this issue to me
