### ISSUE TITLE
Text Editor Website

### ISSUE THREAD

**Issue by singhcoder694** [Kritika30032002/ReactCreations#146]
### DESCRIPTION

It is a text editor website where user can come and edit basic things like converting character to capital, smaller etc. This website has both light and dark mode enabled.
<img width="924" alt="Screenshot 2023-12-22 214903" src="https://github.com/Kritika30032002/ReactCreations/assets/114601400/d86bd078-1a6a-44c1-b0ea-f4886783f3a1">
<img width="945" alt="Screenshot 2023-12-22 214926" src="https://github.com/Kritika30032002/ReactCreations/assets/114601400/3ee232d6-3830-4940-b7ba-6ec33638ec19">

**Comment by Bayyana-kiran** [comment]
Hello , I would to work on this issue can u please assign me and also describe about the issue once again?

**Comment by Kritika30032002** [comment]
it is mentioned above

**Comment by Bayyana-kiran** [comment]
So, need to create a web app which is mentioned above right? i don't see that project in repo

**Comment by Kritika30032002** [comment]
If it was already present then why this issue had been opened up ? It is not present in repo that's why this can added to repo.
You can make this website by using react in it(If you can).

**Comment by Bayyana-kiran** [comment]
Ohh okay tq for clarification 😊

**Comment by Bhupendra3444** [comment]
hey @Kritika30032002  Please assign me this task under iwoc. I want to work on it.

**Comment by Bayyana-kiran** [comment]
<img width="903" alt="Screenshot 2024-01-18 163639" src="https://github.com/Kritika30032002/ReactCreations/assets/99533113/88263897-2cfa-4718-b024-e8a2b47df29d">
is it ok?

**Comment by Bayyana-kiran** [comment]
@Kritika30032002 kindly reply once

**Comment by Kritika30032002** [comment]
does all functions working?

**Comment by Bayyana-kiran** [comment]
Yes @Kritika30032002

**Comment by Bayyana-kiran** [comment]
@Kritika30032002  Created a PR kindly check :)

**Comment by Bayyana-kiran** [comment]
@Kritika30032002 i didn't got the points can u close this issue
