### ISSUE TITLE
react travel website 

### ISSUE THREAD

**Issue by GAGANRAGHAV** [Kritika30032002/ReactCreations#159]
it is made using --

1.React 
2.Google Maps API
3.APIs for travel information, such as weather, flights, hotels, etc.
4.Firebase
5. Material UI for styling

screenshot --

![image](https://github.com/Kritika30032002/ReactCreations/assets/120806356/5985d8da-0f06-4434-9cd1-09567c0625b7)

**Comment by GAGANRAGHAV** [comment]
MA'AM WHAT IS WRONG IT..PLEASE TELL

**Comment by Kritika30032002** [comment]
you have already added many projects and these much cannot be your made

**Comment by GAGANRAGHAV** [comment]
ma'am some during learning phase some during intern , some during hackathon .. i accept project is not fully made by me but it was a group projects and the whole is done by me only ...and you also closed a pr without merging
