### ISSUE TITLE
Salon Booking Website

### ISSUE THREAD

**Issue by Dhruv127** [Kritika30032002/ReactCreations#184]
Implemented robust user authentication using **Firebase** for secure sign-up and login processes.
Integrated **React**, **MongoDB**, **Express**, and **Bootstrap** to create a dynamic and user-friendly interface.
Crafted a visually appealing shopping cart with seamless navigation for an enhanced user experience.
Prioritized security measures while ensuring smooth functionality, fostering trust and ease of use throughout the platform.

![Screenshot (156)](https://github.com/Kritika30032002/ReactCreations/assets/92450489/edcac2b2-329f-4d3c-bdc7-56e508061985)
![Screenshot (157)](https://github.com/Kritika30032002/ReactCreations/assets/92450489/50095922-aec9-4fd2-82b9-152fb7c75acd)
![Screenshot (158)](https://github.com/Kritika30032002/ReactCreations/assets/92450489/c5b132c7-21d7-46df-a8bc-d9d5cdda4794)

**Comment by Kritika30032002** [comment]
program name?

**Comment by Dhruv127** [comment]
@Kritika30032002  codepeak '23

**Comment by Dhruv127** [comment]
my both the prs , saloon book website and codewithdhruv was merge together , please give points accordingly . If you can also consider giving bonus points for unique idea . @Kritika30032002
