### ISSUE TITLE
Weather App

### ISSUE THREAD

**Issue by rohan17012001** [Kritika30032002/ReactCreations#20]
I want to add a weather application

**Comment by Kritika30032002** [comment]
Is it in react?

**Comment by rohan17012001** [comment]
yes

**Comment by Sa2003hil** [comment]
Please assign me to this **issue #20** . I would like to work on it.

**Comment by Kritika30032002** [comment]
@rohan17012001  r  u working?

**Comment by rohan17012001** [comment]
Yes.

**Comment by Kritika30032002** [comment]
okay

**Comment by Jaimin25** [comment]
I would like to work on this

**Comment by Jaimin25** [comment]
@Kritika30032002 can I make it using nextjs or I have to use react only?

**Comment by Kritika30032002** [comment]
React only

**Comment by Jaimin25** [comment]
@Kritika30032002 ig close this one
