### ISSUE TITLE
Graphical Dashboard

### ISSUE THREAD

**Issue by JiyaGupta-cs** [Kritika30032002/ReactCreations#213]
**Description-**
I want to add a Graphical Dashboard for the user which displays the content with the help of graphs with a stats section, recent activity section, and graph cards
It will also be responsive according to all screen sizes

**Techstack-**
React JS
For Graphs - React ApexCharts

**Screenshots-**

![image](https://github.com/Kritika30032002/ReactCreations/assets/140608790/cbcd08af-baf5-41a8-adc1-f282546a0db9)

![image](https://github.com/Kritika30032002/ReactCreations/assets/140608790/664b4871-8a70-45a8-be3a-15da8033ac98)

**Comment by JiyaGupta-cs** [comment]
@Kritika30032002 Please assign me this issue under IWOC

**Comment by JiyaGupta-cs** [comment]
@Kritika30032002 Please assign me

**Comment by Kritika30032002** [comment]
is it fully functional or just ui based?
