### ISSUE TITLE
Adding Github workflows for issue and pull request

### ISSUE THREAD

**Issue by Kritika30032002** [Kritika30032002/ReactCreations#214]

**Comment by praptisharma28** [comment]
Assign me @Kritika30032002 , I will add the template for both bug and feature.

**Comment by praptisharma28** [comment]
okay I created this issue earlier, may I forget about it sorry, doing the PR . @Kritika30032002

**Comment by praptisharma28** [comment]
> okay I created this issue earlier, may be I forget about it sorry, doing the PR . Also hoping to get a hard tag coz I need to add around 7-8 files into a new folder to add a complete workflow and the folder doesn't exist. @Kritika30032002

done #231 @Kritika30032002
