### ISSUE TITLE
[Feature]: Add the github action workflow for greeting contributors

### ISSUE THREAD

**Issue by praptisharma28** [Kritika30032002/ReactCreations#223]
#Describe your improvement idea or feature request
The current project lacks an automated action to greet contributors. GitHub Actions can significantly enhance project automation. I propose adding a GitHub Action workflow to greet new pull request (PR) and issue creators, fostering a welcoming environment.

#How would you like to see it implemented?
Implement a GitHub Action workflow that triggers on new PRs and issues. The workflow should include a greeting message to acknowledge and appreciate the contributors for their efforts.

**Comment by praptisharma28** [comment]
Please assign me here @Kritika30032002 , will greet the first contributors on your repo.

**Comment by Kritika30032002** [comment]
included in #214
