### ISSUE TITLE
Chatgpt clone with documentation

### ISSUE THREAD

**Issue by praptisharma28** [Kritika30032002/ReactCreations#252]
"ChatGPT Clone is a project designed to replicate the core functionality of ChatGPT, an AI-powered conversational agent developed by OpenAI, along with detailed documentation to guide users and developers through its setup and usage."

**Comment by praptisharma28** [comment]
@Kritika30032002 assign me under iwoc24

**Comment by Kritika30032002** [comment]
techstack?

**Comment by praptisharma28** [comment]
> techstack?

Build on MERN Stack @Kritika30032002

**Comment by praptisharma28** [comment]
@Kritika30032002 please add the hard tag here too, its not showing on my dashboard.
