### ISSUE TITLE
Todo list 

### ISSUE THREAD

**Issue by Swastik200** [Kritika30032002/ReactCreations#4]
Creating  a todo list using react

**Comment by Swastik200** [comment]
Thank you for your response sure

**Comment by Swastik200** [comment]
Plz check and confirm

**Comment by anshulkumarx7** [comment]
Can u please me this??

**Comment by Kritika30032002** [comment]
?

**Comment by Hemant-Lohar** [comment]
I will add todo list project can you please assign me this @Kritika30032002

**Comment by anshulkumarx7** [comment]
> ?

PLEASE ASSIGN ME i WILL BE CREATING A TO-DO LIST
