### ISSUE TITLE
Devloper's Bussiness Webapp

### ISSUE THREAD

**Issue by AaadityaG** [Kritika30032002/ReactCreations#86]
https://github.com/Kritika30032002/ReactCreations/assets/114663382/8b144777-861b-4945-aff9-ac21910402c3

I am participating in Codepeak and KWoC.

**Comment by Kritika30032002** [comment]
in which program you want this to be considered?

**Comment by AaadityaG** [comment]
I am participating in Codepeak and KWoC

**Comment by Kritika30032002** [comment]
only 1

**Comment by Kritika30032002** [comment]
in which you want this to be considered?

**Comment by AaadityaG** [comment]
Okay So consider it for Codepeak

**Comment by YashSachan2** [comment]
@Kritika30032002 Can I work on this issue under Codepeak-23?

**Comment by AaadityaG** [comment]
Its done already.. I think

**Comment by YashSachan2** [comment]
Ohk
