### ISSUE TITLE
Cocktail Project using react with Cocktail API

### ISSUE THREAD

**Issue by DHRUVKHANDELWAL00** [Kritika30032002/ReactCreations#89]

**Comment by DHRUVKHANDELWAL00** [comment]
hey @Kritika30032002  please assign me

**Comment by Kritika30032002** [comment]
program name?

**Comment by DHRUVKHANDELWAL00** [comment]
@Kritika30032002  Codepeak

**Comment by atbalaji** [comment]
Hi @Kritika30032002 . I would love to work on this. Just for confirmation is this Cocktail Project something similar to https://www.thecocktaildb.com/ ?

**Comment by Kritika30032002** [comment]
don't think so
i think this issue can be closed as issue creater hasn't specified anything about this
